added landing page component and related css
the-10x-academy/apprenticeship-team-c pull request #5
Opened 2021-01-30 07:56 UTC by prabal01

This is the same PR as before but this time I did not forked it so that all the other team mates can see it.Please have a look and let me know if it needs any changes

2021-01-31 07:01 UTC, imdy3011 approved these changes
In img tag use alt. If image not load then user can understand what is this space for.

2021-01-31 08:02 UTC, jasce requested changes
I tried running your code on local but it is not rendering your landiing Page. I think you have not used initialiised your landing Page component in code

2021-02-01 07:41 UTC, prabal01 commented
> This is the same PR as before but this time I did not forked it so that all the other team mates can see it.Please have a look and let me know if it needs any changes

-added alt tag for image 
-connected the landing page to the homepage so that it could lode when you start server

2021-02-01 08:17 UTC, imdy3011 approved these changes

2021-02-02 04:41 UTC, jasce approved these changes

2021-02-02 04:41 UTC, merged